name: MdView CI

on: [push, pull_request]

jobs:

  package:
    name: MdView
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build
      run: dotnet build MdView.sln --configuration Release

  android_sample:
    name: Android sample app
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore
      run: |
        cd MdView.Sample/
        msbuild /t:restore MdView.Sample.Android/MdView.Sample.Android.csproj

    - name: Build
      run: |
        cd MdView.Sample/
        msbuild MdView.Sample.Android/MdView.Sample.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release

  ios_sample:
    name: iOS sample app
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore
      run: |
        cd MdView.Sample/
        msbuild /t:restore MdView.Sample.iOS/MdView.Sample.iOS.csproj

    - name: Build
      run: |
        cd MdView.Sample/
        msbuild MdView.Sample.iOS/MdView.Sample.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
